---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      import/no-absolute-path:
          enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*"
exclude_paths:
  - "webpack/*"
